---

- name: install mapserver and libgdal
  apt:
    name:
    - cgi-mapserver
    - libgdal-dev
    state: latest

- name: create imageserver fcgi directory
  file: path={{ giscube_fcgis_directory }}/giscube_imageserver state=directory
      owner=www-data
      group=www-data
      mode=0755

- name: copy imageserver fcgi configuration
  copy:
    src=data/fcgis/imageserver/uwsgi_ondemand.ini
    dest={{ giscube_fcgis_directory }}/giscube_imageserver/
    owner=www-data
    group=www-data
    mode=0644
